name: Java CI with Maven

on:
  push:
    branches: [ "for_action" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up JBR17
      run: |
        curl -L -o jbr.tar.gz https://cache-redirector.jetbrains.com/intellij-jbr/jbrsdk-17.0.9-linux-x64-b1087.7.tar.gz
        tar -xzf jbr.tar.gz
        echo `ls -l`
        echo "JAVA_HOME=$PWD/jbrsdk-17.0.9-linux-x64-b1087.7" >> $GITHUB_ENV
        echo "PATH=$PWD/jbr_fd-17.0.9-linux-x64-b1087.7/bin:$PATH" >> $GITHUB_ENV

    - name: Verify Java version
      run: java -version

    - name: Build with Maven
      run: mvn clean test

    # Optional: Uploads the full dependency graph to GitHub to improve the quality of Dependabot alerts this repository can receive
    - name: Update dependency graph
      uses: advanced-security/maven-dependency-submission-action@571e99aab1055c2e71a1e2309b9691de18d6b7d6
