name: Java CI with Maven

on:
  push:
    branches: [ "master","master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        ref: master

    - name: Set up JBR17
      run: |
        curl -L -o jdk.tar.gz https://github.com/TravaOpenJDK/trava-jdk-11-dcevm/releases/download/dcevm-11.0.15%2B1/Openjdk11u-dcevm-linux-x64.tar.gz
        tar -xzf jdk.tar.gz
        export JAVA_HOME=$PWD/dcevm-11.0.15+1
        export PATH=$JAVA_HOME/bin:$PATH
        java -version
      shell: bash

    - name: Maven install
      run: |
        export JAVA_HOME=$PWD/dcevm-11.0.15+1
        export PATH=$JAVA_HOME/bin:$PATH
        java -version
        mvn install -DskipTests && cd plugin/hotswap-agent-mybatis-plugin && mvn test
      shell: bash

    # Optional: Uploads the full dependency graph to GitHub to improve the quality of Dependabot alerts this repository can receive
    - name: Update dependency graph
      uses: advanced-security/maven-dependency-submission-action@571e99aab1055c2e71a1e2309b9691de18d6b7d6
